version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb 
    ports:
      - "27018:27018"
    volumes: 
      - mongodata:/dbmongodata/db
    networks:
      - docker

  shop-service:
    container_name: shop-service
    build: .
    depends_on:
      - mongodb 
    ports:
      - "7070:7070"
    networks:
      - docker
      
networks:
  docker:
    driver: bridge

volumes:
  mongodata:
